#!/usr/bin/env node

var repl = require('repl')

var hs = require('./hs')
var c = hs.core

var replServer = repl.start({
  prompt: 'hsci> ',
})
require('repl.history')(replServer, process.env.HOME + '/.node_history')

replServer.context.hs = hs
replServer.context.c = c

